services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: swizjobs-bot
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-username} -d swizjobs-bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  swiss-job-bot:
    build: .
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@postgres:5432/swizjobs-bot
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      APIFY_API_TOKEN: ${APIFY_API_TOKEN}
      SERPAPI_API_KEY: ${SERPAPI_API_KEY}
      NODE_ENV: production
      TZ: Europe/Zurich
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
